config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  get "examples", :to=>"home#examples", :as=>"examples"
  post "solve", :to=>"home#solve", :as=>"solve"
  post "show", :to=>"home#show", :as=>"show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include HTTParty

  def index

  end

  def solve
    events_info = params["_json"]
    events = Hash.new
    events_info.each do |event|
      id = event["id"].to_s.split("#")[0]
      start_date = Time.at(event["start_date"] / 1000).utc
      end_date = Time.at(event["end_date"] / 1000).utc  
      if not events.key?(id)
        events[id] = Hash.new
        events[id]["start"] =  start_date.hour * 60 + start_date.min
        events[id]["end"] =  end_date.hour * 60 + end_date.min
        if end_date.hour == 0 and end_date.min == 0
          events[id]["end"] =  24 * 60
        end
        events[id]["date"] = [(start_date.to_date - Date.new(2021,5,31)).to_i]
        events[id]["text"] = event["text"]
      else
        if (start_date.hour * 60 + start_date.min) != events[id]["start"]
          render plain: 'Error: series invalid or inconsistent', layout: "no_toolbar"
          return
        else
          events[id]["date"].append((start_date.to_date - Date.new(2021,5,31)).to_i)
        end
      end

      if start_date.to_date != end_date.to_date
        if not ((end_date.to_date == start_date.to_date + 1) and end_date.hour == 0 and end_date.min == 0) #boundary exception
          render plain: 'Error: events spanning multiple days are not supported', layout: "no_toolbar"
          return
        end 
      end
    end

    #puts "events"
    #puts events
    groups = Hash.new
    events.each do |_, event|
      if not groups.key?(event["text"])
        groups[event["text"]] = {length: event["end"] - event["start"], data: []}
      end
      if groups[event["text"]][:length] != (event["end"] - event["start"])
        #puts groups[event["text"]][:length]
        #puts (event["end"] - event["start"])
        render plain: 'Error: events with the same name have to have the same length', layout: "no_toolbar"
        return
      end
      groups[event["text"]][:data].append([[event["start"]], event["date"]])
    end
    
    #puts "groups"
    #puts groups

    body = [[], [], []]
    groups.each do |key, value|
      body[0].append(value[:data])
      body[1].append(value[:length])
      body[2].append(key)
    end

    results = HTTParty.post("http://fathomless-everglades-11877.herokuapp.com/rdsolve",
      :body => {:schedules => body[0], 
               :lengths => body[1]}.to_json,
               :headers => {'Content-Type' => 'application/json'})

    if results.nil?
      render plain: 'Error: all events could not be accommodated', layout: "no_toolbar"
      return
    end

    #Transform into {text, start, end} hashes               
    @hashes = []
    results.each_with_index do |result, i|
      start_time = result[0]
      end_time = result[0] + body[1][i]
      text = body[2][i]
      (1...result.length).each do |j|
        date = Date.new(2021,5,31) + result[j]
        start_date = DateTime.new(date.year, date.month, date.day, start_time / 60, start_time % 60)
        end_date = DateTime.new(date.year, date.month, date.day, end_time / 60, end_time % 60)
        @hashes.append({text: text, start_date: start_date.strftime('%Y-%m-%d %H:%M'), end_date: end_date.strftime('%Y-%m-%d %H:%M')})
      end
    end

    #puts results.to_s
    #puts @hashes
    #puts body.to_s

    render :show, layout: "no_toolbar"
    #render plain: results
    #return
  end

  def show
    @hashes = params["_json"]
    render :show, layout: "no_toolbar"
  end

  def examples

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_scheduler.html.erb
<div id="<%= schedule_id %>" class="dhx_cal_container vh-100 w-100">
    <div hidden class="dhx_cal_navline"></div>
    <div class="dhx_cal_header"></div>
    <div class="dhx_cal_data"></div>
</div>
 
<script>
    scheduler.config.limit_start = new Date(2021,4,31);
    scheduler.config.limit_end = new Date(2021,5,7);
    scheduler.config.lightbox.sections = [
        {name:"description", height:130, map_to:"text", type:"textarea" , focus:true},
        {name:"recurring", type:"recurring", map_to:"rec_type", button:"recurring", 
        form:"my_recurring_form"},
        {name:"time", height:72, type:"time", map_to:"auto"}
    ];
    scheduler.templates.week_scale_date = function(date){
        var format = scheduler.date.date_to_str("%l");
        return format(date);
    };

    function hashColor(input) {
        var hash = 0;
        for (var i = 0; i < input.length; i += 1) {
            hash = input.charCodeAt(i) + ((hash << 5) - hash);
            hash = hash & hash;
        }
        var color = '#';
        for (var i = 0; i < 3; i += 1) {
            var value = (hash >> (i * 8)) & 255;
            color += ('00' + value.toString(16)).substr(-2);
        }
        return color;
    }
    scheduler.attachEvent("onEventAdded",function(id,ev){
        scheduler.getEvent(id).color = hashColor(ev.text);
        scheduler.updateEvent(id);
        return true;
    });
    scheduler.attachEvent("onEventChanged",function(id,ev){
        scheduler.getEvent(id).color = hashColor(ev.text);
        scheduler.updateEvent(id);
        return true;
    });
    scheduler.attachEvent("onLightbox", function (id){
        document.getElementsByName("date_of_end")[0].value = "06.07.2021";
        return true;
    });
    scheduler.attachEvent("onBeforeEventChanged",function(dev){
        var parts = scheduler.getState().drag_id.toString().split("#");
        if (parts.length > 1) {
    
            var series = this.getEvent(parts[0]);
    
            series.start_date.setHours(dev.start_date.getHours());
            series.start_date.setMinutes(dev.start_date.getMinutes());
            series.event_length = (dev.end_date - dev.start_date) / 1000;
    
            setTimeout(function(){
                scheduler.addEvent(series);
            }, 1);
    
            return false;
        }
        return true;
    });
    scheduler.config.details_on_dblclick = true;
	scheduler.config.details_on_create = true;
    scheduler.xy.nav_height = 0;
    scheduler.init("<%= schedule_id %>", new Date(2021,4,31), "week");
</script>

<div hidden>
    <div class="dhx_form_repeat" id="my_recurring_form"> 
    <form>
        <input type="hidden" name="repeat" value="week" />
        <div id="dhx_repeat_week">
        Repeat on days:<br />

        <label><input type="checkbox" name="week_day" value="1" />Monday</label>
        <label><input type="checkbox" name="week_day" value="2" />Tuesday</label>
        <label><input type="checkbox" name="week_day" value="3" />Wednesday</label>
        <label><input type="checkbox" name="week_day" value="4" />Thursday</label>
        <label><input type="checkbox" name="week_day" value="5" />Friday</label>
        <label><input type="checkbox" name="week_day" value="6" />Saturday</label>
        <label><input type="checkbox" name="week_day" value="0" />Sunday</label>
        <input type="hidden" name="week_count" value="1" />
        </div>
    
        <input hidden name="end"/>
        <input hidden name="end"/>
        <input hidden name="end" checked=""/>
        <input hidden type="text" name="date_of_end" value="undefined"/>
    </form>
    </div>
</div>

app/views/home/examples.html.erb
<div class='container-fluid my-3'>
    <h3>Class Schedule Example</h3>
</div>

<script>
    function displaySolution() {
        var offset = new Date().getTimezoneOffset();

        solution = [
            {text: "Physics 7", start_date: "2021-06-01 8:00", end_date: "2021-06-01 9:30"},
            {text: "Physics 7", start_date: "2021-06-03 8:00", end_date: "2021-06-03 9:30"},
            {text: "Discussion", start_date: "2021-05-31 9:00", end_date: "2021-05-31 10:00"},
            {text: "Lunch", start_date: "2021-05-31 11:00", end_date: "2021-05-31 12:00"},
            {text: "Lunch", start_date: "2021-06-01 11:00", end_date: "2021-06-01 12:00"},
            {text: "Lunch", start_date: "2021-06-02 11:00", end_date: "2021-06-02 12:00"},
            {text: "Lunch", start_date: "2021-06-03 11:00", end_date: "2021-06-03 12:00"},
            {text: "Lunch", start_date: "2021-06-04 11:00", end_date: "2021-06-04 12:00"},
            {text: "English 3", start_date: "2021-05-31 12:00", end_date: "2021-05-31 13:00"},
            {text: "English 3", start_date: "2021-06-02 12:00", end_date: "2021-06-02 13:00"},
            {text: "English 3", start_date: "2021-06-04 12:00", end_date: "2021-06-04 13:00"},
            {text: "Compsci 101", start_date: "2021-05-31 13:00", end_date: "2021-05-31 14:00"},
            {text: "Compsci 101", start_date: "2021-06-02 13:00", end_date: "2021-06-02 14:00"},
            {text: "Compsci 101", start_date: "2021-06-04 13:00", end_date: "2021-06-04 14:00"},
            {text: "Music 25", start_date: "2021-06-01 13:00", end_date: "2021-06-01 15:00"},
            {text: "Music 25", start_date: "2021-06-03 13:00", end_date: "2021-06-03 15:00"}
        ];

        fetch("<%= show_path %>", {
            method: "POST", 
            headers: {
                'Content-Type': 'application/json'
        },
            body: JSON.stringify(solution)
        }).then(async res => {
            const text = await res.text();
            if (res.status == 200) {
                var iframe = document.getElementById('solution_scheduler');
                iframe.contentWindow.document.open();
                iframe.contentWindow.document.write(text);
                iframe.contentWindow.document.close();
            }
        });
    }

    function initExample() {
        function hashColor(input) {
            var hash = 0;
            for (var i = 0; i < input.length; i += 1) {
                hash = input.charCodeAt(i) + ((hash << 5) - hash);
                hash = hash & hash;
            }
            var color = '#';
            for (var i = 0; i < 3; i += 1) {
                var value = (hash >> (i * 8)) & 255;
                color += ('00' + value.toString(16)).substr(-2);
            }
            return color;
        }
        scheduler.clearAll();
        scheduler.config.readonly = true;
        scheduler.parse([
            {text: "Physics 7", start_date: "2021-06-01 8:00", end_date: "2021-06-01 9:30", color: hashColor("Physics 7")},
            {text: "Physics 7", start_date: "2021-06-03 8:00", end_date: "2021-06-03 9:30", color: hashColor("Physics 7")},
            {text: "Physics 7", start_date: "2021-05-31 11:00", end_date: "2021-05-31 12:30", color: hashColor("Physics 7")},
            {text: "Physics 7", start_date: "2021-06-02 11:00", end_date: "2021-06-02 12:30", color: hashColor("Physics 7")},
            {text: "Physics 7", start_date: "2021-06-01 11:00", end_date: "2021-06-01 12:30", color: hashColor("Physics 7")},
            {text: "Physics 7", start_date: "2021-06-03 11:00", end_date: "2021-06-03 12:30", color: hashColor("Physics 7")},
            {text: "Discussion", start_date: "2021-05-31 9:00", end_date: "2021-05-31 10:00", color: hashColor("Discussion")},
            {text: "Discussion", start_date: "2021-06-01 9:00", end_date: "2021-06-01 10:00", color: hashColor("Discussion")},
            {text: "Discussion", start_date: "2021-06-02 9:00", end_date: "2021-06-02 10:00", color: hashColor("Discussion")},
            {text: "Discussion", start_date: "2021-06-03 9:00", end_date: "2021-06-03 10:00", color: hashColor("Discussion")},
            {text: "Discussion", start_date: "2021-06-04 9:00", end_date: "2021-06-04 10:00", color: hashColor("Discussion")},
            {text: "Lunch", start_date: "2021-05-31 10:00", end_date: "2021-05-31 11:00", color: hashColor("Lunch")},
            {text: "Lunch", start_date: "2021-06-01 10:00", end_date: "2021-06-01 11:00", color: hashColor("Lunch")},
            {text: "Lunch", start_date: "2021-06-02 10:00", end_date: "2021-06-02 11:00", color: hashColor("Lunch")},
            {text: "Lunch", start_date: "2021-06-03 10:00", end_date: "2021-06-03 11:00", color: hashColor("Lunch")},
            {text: "Lunch", start_date: "2021-06-04 10:00", end_date: "2021-06-04 11:00", color: hashColor("Lunch")},
            {text: "Lunch", start_date: "2021-05-31 11:00", end_date: "2021-05-31 12:00", color: hashColor("Lunch")},
            {text: "Lunch", start_date: "2021-06-01 11:00", end_date: "2021-06-01 12:00", color: hashColor("Lunch")},
            {text: "Lunch", start_date: "2021-06-02 11:00", end_date: "2021-06-02 12:00", color: hashColor("Lunch")},
            {text: "Lunch", start_date: "2021-06-03 11:00", end_date: "2021-06-03 12:00", color: hashColor("Lunch")},
            {text: "Lunch", start_date: "2021-06-04 11:00", end_date: "2021-06-04 12:00", color: hashColor("Lunch")},
            {text: "English 3", start_date: "2021-05-31 11:00", end_date: "2021-05-31 12:00", color: hashColor("English 3")},
            {text: "English 3", start_date: "2021-06-02 11:00", end_date: "2021-06-02 12:00", color: hashColor("English 3")},
            {text: "English 3", start_date: "2021-06-04 11:00", end_date: "2021-06-04 12:00", color: hashColor("English 3")},
            {text: "English 3", start_date: "2021-05-31 12:00", end_date: "2021-05-31 13:00", color: hashColor("English 3")},
            {text: "English 3", start_date: "2021-06-02 12:00", end_date: "2021-06-02 13:00", color: hashColor("English 3")},
            {text: "English 3", start_date: "2021-06-04 12:00", end_date: "2021-06-04 13:00", color: hashColor("English 3")},
            {text: "English 3", start_date: "2021-05-31 13:00", end_date: "2021-05-31 14:00", color: hashColor("English 3")},
            {text: "English 3", start_date: "2021-06-02 13:00", end_date: "2021-06-02 14:00", color: hashColor("English 3")},
            {text: "English 3", start_date: "2021-06-04 13:00", end_date: "2021-06-04 14:00", color: hashColor("English 3")},
            {text: "Compsci 101", start_date: "2021-05-31 13:00", end_date: "2021-05-31 14:00", color: hashColor("Compsci 101")},
            {text: "Compsci 101", start_date: "2021-06-02 13:00", end_date: "2021-06-02 14:00", color: hashColor("Compsci 101")},
            {text: "Compsci 101", start_date: "2021-06-04 13:00", end_date: "2021-06-04 14:00", color: hashColor("Compsci 101")},
            {text: "Music 25", start_date: "2021-06-01 09:00", end_date: "2021-06-01 11:00", color: hashColor("Music 25")},
            {text: "Music 25", start_date: "2021-06-03 09:00", end_date: "2021-06-03 11:00", color: hashColor("Music 25")},
            {text: "Music 25", start_date: "2021-06-01 11:00", end_date: "2021-06-01 13:00", color: hashColor("Music 25")},
            {text: "Music 25", start_date: "2021-06-03 11:00", end_date: "2021-06-03 13:00", color: hashColor("Music 25")},
            {text: "Music 25", start_date: "2021-06-01 13:00", end_date: "2021-06-01 15:00", color: hashColor("Music 25")},
            {text: "Music 25", start_date: "2021-06-03 13:00", end_date: "2021-06-03 15:00", color: hashColor("Music 25")},
        ],"json");
    }

    initExample();
    window.addEventListener('load', initExample);
</script>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-5 min-vh-100">
            <div class="card border-primary h-100">
                <div class="card-header bg-primary text-light">Set Schedules</div>
                <div class="card-body">
                    <%= render partial: "scheduler", locals: {schedule_id: "example_schedule"} %>
                </div>
            </div>
        </div>
        <div class="col-md-2 my-auto">
            <div class="card">
                <button id="solve_btn" type="button" class="btn btn-lg btn-block btn-outline-primary align-self-center" onclick="displaySolution();">Solve!</button>
            </div>
        </div>
        <div class="col-md-5 min-vh-100">
            <div class="card border-primary h-100">
                <div class="card-header bg-primary text-light">Solution</div>
                <div class="card-body">
                    <iframe id="solution_scheduler" width="100%" height="100%" frameBorder="0">
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<div class='container-fluid my-3'>
    <div class="row">
        <div class="col-10">
            <h1>Schedule Solver</h1>
        </div>
        <div class="col-2">
            <button type="button" class="btn btn-lg btn-block btn-outline-success" onclick="exportSolution();">Save</button>
        </div>
    </div>
</div>

<script>
    function displaySolution() {
        var offset = new Date().getTimezoneOffset();
        let events = scheduler.getEvents(new Date(2021,4,31), new Date(2021,5,7));

        var json = [];
        for (var i = 0; i < events.length; i += 1) {
            let map = {};
            map["start_date"] = Date.parse(events[i]["start_date"]) - offset * 60000;
            map["end_date"] = Date.parse(events[i]["end_date"]) - offset * 60000;
            map["id"] = events[i]["id"];
            map["text"] = events[i]["text"];
            json.push(map);
        }

        fetch("<%= solve_path %>", {
            method: "POST", 
            headers: {
                'Content-Type': 'application/json'
        },
            body: JSON.stringify(json)
        }).then(async res => {
            const text = await res.text();
            if (res.status == 200) {
                var iframe = document.getElementById('solution_scheduler');
                iframe.contentWindow.document.open();
                iframe.contentWindow.document.write(text);
                iframe.contentWindow.document.close();
            }
        });
    }

    function exportSolution() {
        if (document.getElementById('solution_scheduler').contentWindow.scheduler) {
            document.getElementById('solution_scheduler').contentWindow.scheduler.exportToPNG();
        }
    }

    scheduler.config.readonly = false;
    scheduler.clearAll();
    scheduler.config.dblclick_create = true;
</script>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-5 min-vh-100">
            <div class="card border-primary h-100">
                <div class="card-header bg-primary text-light">Set Schedules</div>
                <div class="card-body">
                    <%= render partial: "scheduler", locals: {schedule_id: "show_schedule"} %>
                </div>
            </div>
        </div>
        <div class="col-md-2 my-auto">
            <div class="card">
                <button id="solve_btn" type="button" class="btn btn-lg btn-block btn-outline-primary align-self-center" onclick="displaySolution();">Solve!</button>
                <button type="button" class="btn btn-lg btn-block btn-outline-danger align-self-center" onclick="scheduler.clearAll();">Clear</button>
            </div>
        </div>
        <div class="col-md-5 min-vh-100">
            <div class="card border-primary h-100">
                <div class="card-header bg-primary text-light">Solution</div>
                <div class="card-body">
                    <iframe id="solution_scheduler" width="100%" height="100%" frameBorder="0">
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/show.html.erb
<%= render partial: "scheduler", locals: {schedule_id: "show_schedule"} %>

<script>
    function hashColor(input) {
        var hash = 0;
        for (var i = 0; i < input.length; i += 1) {
            hash = input.charCodeAt(i) + ((hash << 5) - hash);
            hash = hash & hash;
        }
        var color = '#';
        for (var i = 0; i < 3; i += 1) {
            var value = (hash >> (i * 8)) & 255;
            color += ('00' + value.toString(16)).substr(-2);
        }
        return color;
    }
    //TODO: populate from instance variables via controller
    scheduler.parse([
        <% @hashes.each_with_index do |hash, i| %>
            <% text = "{text: \"#{hash[:text]}\", start_date: \"#{hash[:start_date]}\", end_date: \"#{hash[:end_date]}\", color: hashColor(\"#{hash[:text]}\")}" %>
            <% if i < @hashes.length - 1 %>
                <% text = text + "," %>
            <% end %>
            <%= text.html_safe %>
        <% end %>
    ],"json");
    scheduler.config.readonly = true;
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schedule Solver</title>
    <%= favicon_link_tag "logo.svg" %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%= stylesheet_link_tag 'dhtmlxscheduler_material',media:'all','data-turbolinks-track'=>true %>
    <%= javascript_include_tag 'dhtmlxscheduler', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'ext/dhtmlxscheduler_limit', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'ext/dhtmlxscheduler_recurring', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'ext/dhtmlxscheduler_readonly', 'data-turbolinks-track' => true %>
  </head>

  <nav class="navbar navbar-light shadow-sm navbar-expand-lg">
    <a class="navbar-brand mb-0 h1 text-center align-middle" href="/">
        <%= image_tag("logo.svg", height: '48', width: '48', class: "d-inline-block align-middle") %>    
        Schedule Solver
    </a>

    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
        </li>
    </ul>

    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="/examples">Examples</a>
        </li>
    </ul>
  </nav>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/no_toolbar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schedulerrails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%= stylesheet_link_tag 'dhtmlxscheduler_material',media:'all','data-turbolinks-track'=>true %>
    <%= javascript_include_tag 'dhtmlxscheduler', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'ext/dhtmlxscheduler_limit', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'ext/dhtmlxscheduler_recurring', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'ext/dhtmlxscheduler_export', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>